version = "3.11.1"
runner.dialect = scala3
maxColumn = 100
rewrite.rules = [RedundantBraces, SortModifiers]
project.excludeFilters = [
  "vendor/.*",
  "docs/benchmarks/receipts/.*",
  "target/.*",
  "modules/.*/target/.*"
]
