java.version=openjdk version "21.0.11" 2026-04-21 LTS
node.version=v24.1.0
sbt.version=1.10.5
scala.version=3.7.4
scalajs.version=1.22.0
candidate.version=0.1.0-RC1
repository=isolated temporary Maven repository
commit=026667c57dca28cfb768dbfb504270c1ec38a719
worktree=dirty
