java.version=openjdk version "22" 2024-03-19
node.version=v24.1.0
sbt.version=1.10.5
scala.version=3.7.4
scalajs.version=1.22.0
candidate.version=0.1.0-RC1
repository=isolated temporary Maven repository
commit=49a2025fe913a146fce4e6f7f4d85c3775ec007b
worktree=dirty
